### PR TITLE
IOS-net: Add 2 stations, group stations in file, standardize

### PR DESCRIPTION
**Pull request by bilbaoba**
Hi Adam,

We've recently added 2 new stations on the French island of Mayotte.

This PR includes:

- Addition of the 2 new stations
- Grouping of all IOS-net stations in the `solarstations.csv` file
- Standardization of information across stations (URL, comments with DOI)
- Correction in the Instrumentation column (UV data not available for all stations)

I hope this PR meets your requirements; please feel free to let me know if any adjustments are needed.

Best regards, and thank you for your work on solarstations.

### CODE REVIEW

**Comment by bilbaoba** [comment]
I read your discussion in PR #246 about how Reunion should be listed.

Mayotte and Reunion are both French overseas departments. Therefore, you could consider setting the country as France for accuracy. The only complication is that their continent is Africa.

I'll let you decide what you prefer

**Comment by AdamRJensen** [comment]
@bilbaoba What are the names of the two new stations? Is it Dembeni and Ouangani (it's a bit hard to detect given the large change in the diff)?

A huge thanks for these contributions!

**Comment by bilbaoba** [comment]
Yes, in Dembeni and Ouanagni. We installed it this past weekend. It was one of the last populated areas where we were not yet present in the Southwest Indian Ocean (Mayotte).

Data are already available on our THREDDS server and tools: https://galilee.univ-reunion.fr/thredds/catalog/dataStations/Mayotte/catalog.html

DOIs will be generated later when the dataset becomes more extensive.

**Comment by AdamRJensen** [comment]
@bilbaoba thank you very much for this PR!

**Pull request merged**
