### PR TITLE
Update map legend markers to match markers on the map

### LINKED ISSUE #96: Fix legend in the intro map
Duplicate of #3 

The legend in the intro map is currently not showing correctly.

Also, consider changing the legend title to "Station status" and making three bullets - Active, inactive, and unknown.

image

### PR DESCRIPTION
**Pull request by kandersolar**
Closes #96, using part of #117.

Instead of using font-awesome symbols (the existence of which varies across font-awesome versions, as noted in #96), this copies how the map is currently displaying the symbols (SVG).

### CODE REVIEW

**Comment by kandersolar** [comment]
PR build: https://solarstations--189.org.readthedocs.build/en/189/intro.html

image

**Comment by IoannisSifnaios** [comment]
Looks great @kandersolar! There are also broken legends on other pages though (i.e., BSRN, MIDC, SRML). Could you maybe fix these too?

**Comment by kandersolar** [comment]
A very good point @IoannisSifnaios :) Rather than continue messing with HTML in each notebook, I have made a reusable `make_legend` utility function that all notebooks can use.  I think all legends are working now.

**Review by AdamRJensen — APPROVED** [review]
Thank you @kandersolar <3

**Pull request merged**
