### PR TITLE
Addition of Plataforma de Almeria station

### LINKED ISSUE #64: Add station at Plataforma Solar de Almería
Details:

Plataforma Solar de Almería,,Almeria,Spain,,,,,,,,https://www.psa.es/en/facilities/meteo/meteo.php,,1,Thermopile,

### LINKED ISSUE #76: CIEMAT - Platform de Almeria
image

Fig. 1: Test bench at CIEMAT’s Plataforma Solar de Almería for various simple diffuse or direct irradiance measurement systems next to the reference station.

Content is from the status report from "IEA PVPS TASK 16 Solar resource for high penetration and large scale applications" - October 9th 2023.

### PR DESCRIPTION
**Pull request by IoannisSifnaios**
Closes #76 
Closes #64 (duplicated)

image

@AdamRJensen can you review this?

### CODE REVIEW

**Comment by IoannisSifnaios** [comment]
Closes issue #76

**Comment by AdamRJensen** [comment]
The acronym seems strange. I would have put down PSA - where did you find the one you used?

**Comment by IoannisSifnaios** [comment]
This is the name they officially use.
See [annual report](url) page 155.

**Comment by IoannisSifnaios** [comment]
> The acronym seems strange. I would have put down PSA - where did you find the one you used?

This is the name they officially use.
See annual report page 155.
https://www.psa.es/en/techrep/2022/Annual_Report_2022.pdf
https://www.dlr.de/en/images/institutes-1/institute-of-solar-research/sf-meteorological-measurement-station-metas

**Pull request merged**
